### ISSUE TITLE
Show resolved tickets

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/r6#4]
Perhaps it should be configurable with a checkbox?

**Comment by zoffixznet** [comment]
At the moment, there are no plans to support resolved/rejected tickets.

**Comment by AlexDaniel** [comment]
Sure. But why?

**Comment by zoffixznet** [comment]
Needless complexity. Anyone interested in past tickets can use RT. In my view, RT's featuritis is the main reason why it sucks. R6 plans to stay far away from that approach.

Also, it would involve more API traffic. I don't know how much RT admins would appreciate it; judging by how slow the API is, the infrastructure providing it may be rather near its limit as it is.
