### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/r6#5]
I see that there's a login form but no HTTPS, this should be fixed.

**Comment by AlexDaniel** [comment]
Ah. I've just read http://perl6.fail/about.

So you don't need HTTPS then, is it correct?

**Comment by zoffixznet** [comment]
> So you don't need HTTPS then, is it correct?

Nope. What for?

**Comment by zoffixznet** [comment]
If by "you" you mean me particularly, to use the release manager features.

Once features requiring the login form are implemented, the site will run on HTTPS

**Comment by zoffixznet** [comment]
Already done.
