### ISSUE TITLE
Understand numeric-only tags

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/r6#9]
I don't know if ``[9999]`` is going to fly in the long run, but right now it exists: https://rt.perl.org/Search/Simple.html?q=%5C9999

**Comment by zoffixznet** [comment]
No, it's stupid tag and adding this feature will make stuff like `@array[42]` look like a tag.

**Comment by AlexDaniel** [comment]
Not if https://github.com/zoffixznet/r6/issues/8 is resolved, but whatever.

**Comment by zoffixznet** [comment]
https://rt.perl.org/Ticket/Display.html?id=132184

**Comment by AlexDaniel** [comment]
\o/
